mediawiki-spamcallback.php: try to update to work recent mediawiki which apparently removed Article::fetchContent()
If you're not on the Not Evil list this resulted in an error when trying to post:
Fatal error: Call to undefined method Article::fetchContent() in /home/james_paige/rpg.hamsterrepublic.com/ohrrpgce/mediawiki-spamcallback.php on line 87

Haven't tested this fix; I can't.

git-svn-id: https://rpg.hamsterrepublic.com/source/web@8235 7d344553-34f0-0310-a9b1-970ce8f1c3a2